name: Hurray
on:
  workflow_run:
    workflows:
      - Hello World
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
    inputs:
      hurray:
        description: Hurray
        required: true

jobs:
  hurray:
    name: Hurray
    runs-on: ubuntu-latest
    steps:
    - name: Hurray
      run: echo I am repo dispatch
