name: Hurray
on:
  workflow_run:
    workflows:
      - Hello World
    branches:
      - main
      - release/**
    types:
      - completed
  workflow_dispatch:
    inputs:
      hurray:
        description: Type 'confirm' to hurray
        required: true
jobs:
  hurray:
    name: Hurray
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event.inputs.hurray == 'confirm' || startsWith(github.ref, 'refs/heads/release')
    steps:
    - name: Hurray
      run: echo I am repo dispatch
