name: PR Test

on:
  pull_request:

jobs:
  test:
    uses: poudelmadhav/github-workflows/.github/workflows/ruby-tests.yml@v5
    with:
      ruby_version: 3.3
      rubocop: false
      rspec: false
