name: Do not run on draft pr
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      already-run: ${{ steps.check-run.outputs.already-run }}
    steps:
      - name: Check if workflow already ran
        id: check-run
        run: echo "::set-output name=already-run::$(git log --pretty=format:%H -1)"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: echo Build successful!
    if: ${{ jobs.build.outputs.already-run != github.sha }} || !github.event.pull_request.draft
