name: Do not run on draft pr
on:
  push:
    branches:
     - not-run-on-draft-pr
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.sha != github.event.pull_request.base.sha && github.run_number != github.event.pull_request.number
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: echo Build successful!
