name: Hello World
on: push

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: echo Hello
        run: echo Hello
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
