name: Hello World
on: push

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo Hello

  world:
    name: World
    needs: hello
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Echo World
        run: echo World
