name: Hello World
on: push

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo Hello
      - uses: actions/checkout@v2
        with:
          bundle-cache: true
          ruby-version: 3.0.3
